### ISSUE TITLE
margin_ranking_报错：All input tensors should have same dimension but got sizes: input1: torch.Size([1024, 1]), input2: torch.Size([1024, 1]), target: torch.Size([1])

### ISSUE THREAD

**Issue by Isaiah-pq** [AnselCmy/MetaR#13]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\GNN\MetaR-master\main.py", line 61, in <module>
    trainer.train()
  File "C:\Users\Administrator\Desktop\GNN\MetaR-master\trainer.py", line 145, in train
    loss, _, _ = self.do_one_step(train_task, iseval=False, curr_rel=curr_rel)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\GNN\MetaR-master\trainer.py", line 124, in do_one_step
    p_score, n_score = self.metaR(task, iseval, curr_rel)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\MetaR\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\MetaR\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\GNN\MetaR-master\models.py", line 110, in forward
    loss = self.loss_func(p_score, n_score, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\MetaR\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\MetaR\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\MetaR\Lib\site-packages\torch\nn\modules\loss.py", line 1338, in forward
    return F.margin_ranking_loss(input1, input2, target, margin=self.margin, reduction=self.reduction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\MetaR\Lib\site-packages\torch\nn\functional.py", line 3362, in margin_ranking_loss
    raise RuntimeError(
RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes: input1: torch.Size([1024, 1]), input2: torch.Size([1024, 1]), target: torch.Size([1])

请问是哪里出了问题？

**Comment by Lei-gift** [comment]
i got same problem

**Comment by YuanMan-00** [comment]
@Isaiah-pq 你好，请问这个维度问题你解决了吗

**Comment by KaileyWang** [comment]
Maybe you can try to modify y = torch.Tensor([1]).to(self.device) to y = torch.ones_like(p_score).to(self.device) to keep the dimensions correct.
